[project]
name = "ml-30days"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "2ndside", email = "aaiqkaa@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "jupyter>=1.1.1",
    "matplotlib>=3.11.2",
    "numpy>=2.5.3",
    "pandas>=3.0.6",
]

[project.scripts]
ml-30days = "ml_30days:main"

[build-system]
requires = ["uv_build>=0.12.24,<0.13.0"]
build-backend = "uv_build"
